"""
Lasso-Penalized Cox Proportional Hazards Model  —  scikit-survival version
===========================================================================
Direct comparison counterpart to the baseline Cox Proportional Hazards model.

Key design choices that mirror the baseline specification:
  • Same data prep, dummy encoding, and complete suite of interaction terms.
  • Manual Standardization (normalize=False): Predictors are standardized 
    (mean 0, sd 1) manually so coefficients can be directly back-transformed.
  • Auto-Scaled Penalty Grid: The λ (alpha) path is natively generated by 
    scikit-survival (n_alphas=100) to perfectly fit the data's sparsity.
  • Verweij Cross-Validation: Overcomes "Small Risk Set Bias" in Cox CV by 
    calculating held-out partial log-likelihood as the difference between 
    full-dataset and training-dataset likelihoods (the glmnet standard).
  • Bootstrap CIs: 95% Confidence Intervals evaluated at λ_min (B=200).
  • Time-Varying Terms: Evaluated as x_j * log(t_i) and residualized against 
    the base term x_j to ensure orthogonal selection by the LASSO penalty.

Scaling note
------------
scikit-survival scales the loss by 1/n_events. Our Verweij implementation 
re-multiplies by event counts to calculate raw log-likelihoods before 
subtraction, ensuring mathematically unbiased cross-validation.

Requirements
------------
    pip install scikit-survival openpyxl matplotlib pandas numpy
"""

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from numpy.linalg import lstsq
from sksurv.linear_model import CoxnetSurvivalAnalysis
from sksurv.util import Surv
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

warnings.filterwarnings("ignore")
np.random.seed(42)

# ═══════════════════════════════════════════════════════════════════════════════
# 1.  DATA PREP
# ═══════════════════════════════════════════════════════════════════════════════
df = pd.read_csv("pad_merged.csv")
df = df.rename(columns={"ref ": "ref", "return ": "return"})

# ── Compute span_days for censored rows using censor_point ───────────────────
# ended = NaN or 0  →  censored; use censor_point as the end date
df["censor_point"] = pd.to_datetime(df["censor_point"])
df["pa_date"]      = pd.to_datetime(df["pa_date"])

censored_mask = df["ended"].isna() | (df["ended"] != 1)
df.loc[censored_mask, "span_days"] = (
    df.loc[censored_mask, "censor_point"]
    - df.loc[censored_mask, "pa_date"]
).dt.days

df["ended"] = df["ended"].fillna(0)

# ── Drop rows where span_days is still missing (no start date available) ─────
n_before = len(df)
df = df.dropna(subset=["span_days"]).copy()
n_after = len(df)
if n_before != n_after:
    print(f"  [INFO] Dropped {n_before - n_after} rows with NaN in "
          f"span_days  ({n_after} rows remain)")

df["event"] = (df["ended"] == 1).astype(bool)   # sksurv needs bool
df["t"]     = df["span_days"].astype(float)


# ── External variable prep (merged dataset) ───────────────────────────────────
# NOTE: gdp_per_capita and gdp_growth in pad_merged.csv are already
#       constructed as one-year lags (t-1) relative to the signing year.
#       No additional lagging is applied here.
df["log_gdp_pc"]   = np.log1p(df["gdp_per_capita"])
df["log_milper"]   = np.log1p(df["milper"])
df["log_bd_total"] = np.log1p(df["bd_best_total"])
df["log_v2regdur"] = np.log1p(df["v2regdur"])

df["unknown_outcome"]    = df["rebel_victory"].isna().astype(float)
df["rebel_victory"]      = df["rebel_victory"].fillna(0).astype(float)
df["government_victory"] = df["government_victory"].fillna(0).astype(float)
df["regime_change"]      = df["regime_change"].fillna(0).astype(float)
df["neighbor_at_war"]    = df["neighbor_at_war"].fillna(0).astype(float)

_ext_impute = [
    "lmtnest", "log_gdp_pc", "gdp_growth", "log_milper",
    "v2x_polyarchy", "log_v2regdur", "v2x_freexp_altinf",
    "v2x_liberal", "v2x_partip", "log_bd_total",
]
for _col in _ext_impute:
    _n = df[_col].isna().sum()
    if _n > 0:
        _med = df[_col].median()
        df[_col] = df[_col].fillna(_med)
        print(f"  [IMPUTE] '{_col}': {_n} NaN → median ({_med:.4f})")

print(f"  External variables prepared. unknown_outcome=1 for "
      f"{int(df['unknown_outcome'].sum())} rows.")

# ── Binary variables (28) ─────────────────────────────────────────────────────
BINARY = [
    "cease", "intarmy", "ddr", "withd", "pp", "intgov", "intciv",
    "elections", "interim", "natalks", "aut", "fed", "ind", "ref",
    "shaloc", "regdev", "cul", "demarcation", "locgov", "amn", "pris",
    "recon", "return", "reaffirm", "outlin", "pko", "gender", "co_impl",
]

# ── Ordinal / continuous ──────────────────────────────────────────────────────
ORDINAL = ["termdur"]

# External variables from merged dataset (literature review factors)
EXTERNAL_BIN = [
    "neighbor_at_war",    # Hegre & Sambanis 2006: war-prone regional neighborhood
    "regime_change",      # Hegre & Sambanis 2006: political volatility
    "rebel_victory",      # Quinn et al. 2007: rebel victory in previous conflict
    "government_victory", # Quinn et al. 2007: government victory in previous conflict
    "unknown_outcome",    # Flag: prior conflict outcome not in UCDP (31 cases)
]
EXTERNAL_CONT = [
    "lmtnest",            # Hegre & Sambanis 2006: % mountainous terrain (log)
    "log_gdp_pc",         # Control: log GDP per capita, lagged one year (t-1)
    "gdp_growth",         # Hegre & Sambanis 2006 + Walter 2015: economic growth (t-1)
    "log_milper",         # Hegre & Sambanis 2006: state military size (log)
    "v2x_polyarchy",      # V-Dem electoral democracy index (0-1)
    "log_v2regdur",       # Regime duration in days (log) — regime stability
    "v2x_freexp_altinf",  # Walter 2015: media freedom (0-1)
    "v2x_liberal",        # Walter 2015: liberal political institutions (0-1)
    "v2x_partip",         # Walter 2015: political participation (0-1)
    "log_bd_total",       # Quinn et al. 2007: prior conflict death toll (log)
]


# ── Multi-level → dummy-encode ────────────────────────────────────────────────
for code, name in [(2, "gov"), (3, "both")]:
    df[f"incomp_{name}"] = (df["incompatibility"] == code).astype(float)
for code, name in [(2, "partial"), (3, "process")]:
    df[f"patype_{name}"] = (df["pa_type"] == code).astype(float)
for code, name in [(2, "frame2"), (3, "frame3")]:
    df[f"frame_{name}"] = (df["frame"] == code).astype(float)
for code, name in [(1, "europe"), (2, "middleeast"), (3, "asia"), (5, "americas")]:
    df[f"region_{name}"] = (df["region"] == code).astype(float)

DUMMIES = [
    "region_europe", "region_middleeast", "region_asia", "region_americas",
    "incomp_gov", "incomp_both",
    "patype_partial", "patype_process",
    "frame_frame2", "frame_frame3",
]
BASE_NAMES = BINARY + EXTERNAL_BIN + ORDINAL + EXTERNAL_CONT + DUMMIES

INTERACTIONS = [
    ("cease",       "pko"),
    ("ddr",         "intarmy"),
    ("ddr",         "intgov"),
    ("pp",          "elections"),
    ("amn",         "co_impl"),
    ("shaloc",      "return"),
    ("aut",         "shaloc"),
    ("withd",       "pko"),
    ("reaffirm",    "co_impl"),
    ("demarcation", "locgov"),
    ("pris",        "amn"),
    ("amn",         "recon"),
    ("intgov",      "natalks"),
]
INTERACTION_NAMES = [f"{a}::{b}" for (a, b) in INTERACTIONS]

COVARIATE_NAMES = BASE_NAMES + INTERACTION_NAMES   # 52 columns

LABELS = {
    "region_europe":      "Region: Europe [ref: Africa]",
    "region_middleeast":  "Region: Middle East [ref: Africa]",
    "region_asia":        "Region: Asia [ref: Africa]",
    "region_americas":    "Region: Americas [ref: Africa]",
    "cease":              "Ceasefire provision",
    "intarmy":            "Integration of armed forces",
    "ddr":                "DDR provision",
    "withd":              "Withdrawal provision",
    "pp":                 "Power-sharing (political)",
    "intgov":             "Integration into government",
    "intciv":             "Civilian power-sharing",
    "elections":          "Elections provision",
    "interim":            "Rebels into interim government",
    "natalks":            "National talks",
    "aut":                "Autonomy provision",
    "fed":                "Federalism provision",
    "ind":                "Independence provision",
    "ref":                "Referendum provision",
    "shaloc":             "Local power-sharing (shaloc)",
    "regdev":             "Regional development",
    "cul":                "Cultural provisions",
    "demarcation":        "Border demarcation",
    "locgov":             "Local governance",
    "amn":                "Amnesty provision",
    "pris":               "Prisoner release",
    "recon":              "Reconciliation",
    "return":             "Return of refugees",
    "reaffirm":           "Reaffirmation of prev. agreement",
    "outlin":             "Outline agreement",
    "pko":                "Peacekeeping operation",
    "gender":             "Gender provision",
    "co_impl":            "Oversight committee",
    "termdur":            "Years since last conflict",
    "neighbor_at_war":    "Neighbor at war (any contiguous)",
    "regime_change":      "Regime change in signing year",
    "rebel_victory":      "Rebel victory (prior conflict)",
    "government_victory": "Government victory (prior conflict)",
    "unknown_outcome":    "Prior conflict outcome unknown",
    "lmtnest":            "Mountainous terrain (log % area)",
    "log_gdp_pc":         "GDP per capita, log (t-1)",
    "gdp_growth":         "GDP growth rate (t-1)",
    "log_milper":         "Military personnel, log (signing yr)",
    "v2x_polyarchy":      "Electoral democracy index (V-Dem)",
    "log_v2regdur":       "Regime duration, log days (V-Dem)",
    "v2x_freexp_altinf":  "Media freedom index (V-Dem)",
    "v2x_liberal":        "Liberal institutions index (V-Dem)",
    "v2x_partip":         "Political participation index (V-Dem)",
    "log_bd_total":       "Prior conflict death toll, log",
    "incomp_gov":         "Incompatibility: Government [ref: Territory]",
    "incomp_both":        "Incompatibility: Both [ref: Territory]",
    "patype_partial":     "Agreement type: Partial [ref: Full]",
    "patype_process":     "Agreement type: Peace Process [ref: Full]",
    "frame_frame2":       "Frame type 2 [ref: Frame 1]",
    "frame_frame3":       "Frame type 3 [ref: Frame 1]",
    "cease::pko":          "Ceasefire  ×  Peacekeeping operation",
    "ddr::intarmy":        "DDR provision  ×  Integration of armed forces",
    "ddr::intgov":         "DDR provision  ×  Interim government",
    "pp::elections":       "Power-sharing (political)  ×  Elections provision",
    "amn::co_impl":        "Amnesty provision  ×  Co-implementation body",
    "shaloc::return":      "Local power-sharing  ×  Return / resettlement",
    "aut::shaloc":         "Autonomy provision  ×  Local power-sharing",
    "withd::pko":          "Withdrawal provision  ×  Peacekeeping operation",
    "reaffirm::co_impl":   "Reaffirm. prev. agreement  ×  Co-implementation body",
    "demarcation::locgov": "Border demarcation  ×  Local governance",
    "pris::amn":           "Prisoner release  ×  Amnesty provision",
    "amn::recon":          "Amnesty provision  ×  Reconciliation",
    "intgov::natalks":     "Interim government  ×  National dialogue / talks",
}

# ── 2. Standardise Base Variables ─────────────────────────────────────────────
X_base_raw = df[BASE_NAMES].values.astype(float)
X_mean = X_base_raw.mean(axis=0)          
X_sd   = X_base_raw.std(axis=0)
X_sd[X_sd == 0] = 1.0                     
X_base_std = (X_base_raw - X_mean) / X_sd  

# ── Build interactions via residualization ────────────────────────────────────
n = X_base_std.shape[0]
ia_resid = []
for a, b in INTERACTIONS:
    col_a    = X_base_std[:, BASE_NAMES.index(a)]
    col_b    = X_base_std[:, BASE_NAMES.index(b)]
    product  = col_a * col_b
    Z        = np.column_stack([np.ones(n), col_a, col_b])
    coefs, _, _, _ = lstsq(Z, product, rcond=None)
    ia_resid.append(product - Z @ coefs)

X_ia     = np.column_stack(ia_resid)
ia_mean  = X_ia.mean(axis=0)
ia_sd    = X_ia.std(axis=0)
ia_sd[ia_sd == 0] = 1.0
X_ia_std = (X_ia - ia_mean) / ia_sd

# Final matrix containing all 52 columns
X_std = np.hstack([X_base_std, X_ia_std])  
X_sd_full = np.concatenate([X_sd, ia_sd])

p = X_std.shape[1]
print(f"  + {len(INTERACTIONS)} interactions (centred × centred) → "
      f"design matrix {p} columns  (standardized)")

# ── Define Survival Target Arrays ─────────────────────────────────────────────
t_all = df["t"].values.astype(float)
e_all = df["event"].values          # bool array for sksurv

# ═══════════════════════════════════════════════════════════════════════════════
# 1c.  TIME-VARYING TERMS FOR PH-VIOLATING COVARIATES
#
#      Variables that fail the PH assumption in the baseline Cox model are
#      entered here as  x_j + x_j*log(t).  The interaction column x_j*log(t)
#      is RESIDUALIZED against x_j before the lasso sees it.
#
#      Why residualize for the lasso specifically?
#      The covariate×covariate interactions above are also residualized, for
#      the same reason: if the lasso zeroes a main effect x_j while retaining
#      x_j*log(t), the surviving interaction coefficient conflates the level
#      of x_j with its time-varying component and becomes uninterpretable.
#      Residualizing x_j*log(t) on [1, x_j] makes the two columns orthogonal
#      so each can be selected or zeroed independently without contaminating
#      the other's estimate.
# ═══════════════════════════════════════════════════════════════════════════════

# ── PH VIOLATORS FROM baseline_cox_full.py ────────────
VIOLATORS = [
    # "elections", 
    # "regdev", 
    # "locgov", 
    # "government_victory", 
    # "log_gdp_pc", 
    # "v2x_polyarchy", 
    # "v2x_liberal", 
    # "region_middleeast", 
    # "incomp_gov", 
    # "ddr::intarmy", 
    # "pp::elections", 
    # "reaffirm::co_impl"
]
# ─────────────────────────────────────────────────────────────────────────────

TV_NAMES = [f"{v}:log(t)" for v in VIOLATORS]

if VIOLATORS:
    # Validate every violator name exists in the current design matrix
    for v in VIOLATORS:
        assert v in COVARIATE_NAMES, (
            f"Violator '{v}' not found in COVARIATE_NAMES after interactions "
            f"were added.  Check spelling matches baseline Cox output exactly."
        )

    # log(t_i + 1): +1 guards against t = 0; uses each subject's own time.
    # See module docstring for the approximation note.
    log_t = np.log(t_all + 1)

    tv_resid_list = []
    for v in VIOLATORS:
        j       = COVARIATE_NAMES.index(v)
        col_x   = X_std[:, j]          # already standardised base term
        col_xlt = col_x * log_t        # raw x * log(t)

        # Residualize: project col_xlt onto span{1, col_x}, keep residual.
        # The residual is orthogonal to col_x by construction, so lasso can
        # select/zero x and x*log(t) independently.
        Z                 = np.column_stack([np.ones(n), col_x])
        coefs_tv, _, _, _ = lstsq(Z, col_xlt, rcond=None)
        tv_resid_list.append(col_xlt - Z @ coefs_tv)

    tv_arr  = np.column_stack(tv_resid_list)   # shape (n, n_violators)
    tv_mean = tv_arr.mean(axis=0)
    tv_sd   = tv_arr.std(axis=0);  tv_sd[tv_sd == 0] = 1.0
    tv_std  = (tv_arr - tv_mean) / tv_sd       # standardise to mean-0, sd-1

    # ── Extend design matrix, name lists, and scale vector ───────────────────
    X_std     = np.hstack([X_std, tv_std])
    X_sd_full = np.concatenate([X_sd_full, tv_sd])

    COVARIATE_NAMES = COVARIATE_NAMES + TV_NAMES
    for v in VIOLATORS:
        tname         = f"{v}:log(t)"
        LABELS[tname] = f"{LABELS[v].split(' [ref')[0]}  ×  log(t)"

    n, p = X_std.shape
    print(f"  + {len(VIOLATORS)} time-varying term(s) "
          f"(x*log(t), residualised against base term) → "
          f"design matrix now {p} columns")
    print(f"  TV terms: {', '.join(TV_NAMES)}")
else:
    print("  VIOLATORS list is empty — no time-varying terms added.")
    print("  Populate VIOLATORS from baseline_cox_full.py PH-test output.")

# ═══════════════════════════════════════════════════════════════════════════════
# 1b.  PRE-FIT CHECKS
# ═══════════════════════════════════════════════════════════════════════════════
print("\n" + "─" * 60)
print("  PRE-FIT DIAGNOSTIC CHECKS")
print("─" * 60)

e_float = e_all.astype(float)

# sksurv structured array — uses original (non-person-period) t_all / e_all
y_surv = Surv.from_arrays(event=e_all, time=t_all)

sep_warnings = 0
print("\n[Check 1] Zero-variance / separation screening:")
# Exclude interaction and TV columns from the binary separation check;
# they are continuous by construction.
non_binary_names = set(INTERACTION_NAMES) | set(TV_NAMES)
for j, name in enumerate(COVARIATE_NAMES):
    col = X_std[:, j]
    if col.std() == 0:
        print(f"  [WARNING] '{name}' has zero variance.")
        sep_warnings += 1
        continue
    if name in non_binary_names:
        continue
    unique_vals = np.unique(col)
    if set(unique_vals).issubset({0.0, 1.0}):
        ev1 = e_float[col == 1].sum() if (col == 1).any() else 0
        ev0 = e_float[col == 0].sum() if (col == 0).any() else 0
        if ev1 == 0 or ev0 == 0:
            print(f"  [WARNING] '{name}' may cause complete separation: "
                  f"events in group-1={int(ev1)}, group-0={int(ev0)}.")
            sep_warnings += 1
if sep_warnings == 0:
    print("  No separation or zero-variance issues detected.")

print(f"\nN={n}  Events={int(e_float.sum())}  "
      f"Censored={int((e_float == 0).sum())}")
print(f"Design matrix: {p} columns  "
      f"({len(BINARY)} PAD binary + {len(EXTERNAL_BIN)} external binary, "
      f"{len(ORDINAL)} ordinal + {len(EXTERNAL_CONT)} external cont., "
      f"{len(DUMMIES)} dummies, {len(INTERACTIONS)} covariate interactions, "
      f"{len(TV_NAMES)} time-varying terms)")

# ═══════════════════════════════════════════════════════════════════════════════
# 2.  CORE HELPER: partial log-likelihood
#     (Breslow, scaled by 1/n_events — identical to custom code)
# ═══════════════════════════════════════════════════════════════════════════════
def partial_loglik(beta, X, t, e):
    """Mean partial log-likelihood (Breslow), scaled by n_events."""
    order   = np.argsort(t)
    X_s     = X[order]; t_s = t[order]; e_s = e[order]
    eta_s   = X_s @ beta
    eta_s  -= eta_s.max()
    exp_s   = np.exp(eta_s)
    cum_exp = np.cumsum(exp_s[::-1])[::-1]
    n_ev    = e_s.sum()
    ll      = 0.0
    for i in range(len(t_s)):
        if e_s[i]:
            ll += eta_s[i] - np.log(cum_exp[i] + 1e-300)
    return ll / (n_ev + 1e-300)

# ═══════════════════════════════════════════════════════════════════════════════
# 3.  λ GRID + SOLUTION PATH (Auto-scaled by scikit-survival)
# ═══════════════════════════════════════════════════════════════════════════════
print("Fitting LASSO path  ...", end="", flush=True)

# Let scikit-survival calculate the optimal data-driven penalty path
m_path = CoxnetSurvivalAnalysis(
    l1_ratio=1.0,
    n_alphas=100,          # Tell it to generate 100 alphas automatically
    alpha_min_ratio=0.01,  # Search down to 1% of the max penalty
    normalize=False,
    fit_baseline_model=False,
    max_iter=100_000,
    tol=1e-8,
)
m_path.fit(X_std, y_surv)

# Extract the automatically generated grid to use in the CV loop
lam_grid = m_path.alphas_
N_LAM = len(lam_grid)

print(" done")
print(f"lambda grid (auto): {lam_grid[0]:.4f} → {lam_grid[-1]:.4f}  ({N_LAM} values)")

# Handle early stopping: pad with the last computed coefficient
path_std = np.zeros((p, len(lam_grid)))
n_fit = m_path.coef_.shape[1]
path_std[:, :n_fit] = m_path.coef_
for j in range(n_fit, len(lam_grid)):
    path_std[:, j] = m_path.coef_[:, -1]

path_orig = path_std / X_sd_full[:, None]   # back-transform to original scale

# ═══════════════════════════════════════════════════════════════════════════════
# 4.  5-FOLD CROSS-VALIDATION  (held-out partial log-likelihood)
#
#     Folds are assigned at the subject level (one row per subject in X_std),
#     which is correct: because the TV terms x_j*log(t_i) are computed from
#     each subject's own time and stored in their row, no leakage can occur
#     across folds.
# ═══════════════════════════════════════════════════════════════════════════════
K         = 5
cv_scores = np.zeros((K, N_LAM))

print(f"\n{K}-fold CV  ...", end="", flush=True)

kf = KFold(n_splits=K, shuffle=True, random_state=42)

for k, (train_idx, val_idx) in enumerate(kf.split(X_std)):
    X_tr = X_std[train_idx];  y_tr = y_surv[train_idx]
    X_va = X_std[val_idx];    t_va = t_all[val_idx]
    e_va = e_float[val_idx]
    
    # Grab training times/events for the Verweij calculation
    t_tr = t_all[train_idx]
    e_tr = e_float[train_idx]

    # Fit the entire sequence of penalties at once for this fold
    m_cv = CoxnetSurvivalAnalysis(
        l1_ratio=1.0,
        alphas=lam_grid,
        normalize=False,
        fit_baseline_model=False,
        max_iter=100_000,
        tol=1e-7,
    )
    m_cv.fit(X_tr, y_tr)
    
    n_fit_cv = m_cv.coef_.shape[1]

    # Evaluate the validation log-likelihood for each penalty level
    for j in range(len(lam_grid)):
        col_idx = min(j, n_fit_cv - 1)
        beta_j = m_cv.coef_[:, col_idx]
        
        # ── THE VERWEIJ FIX (Verweij & van Houwelingen, 1993) ────────────────
        # Calculating Cox partial log-likelihood directly on small validation 
        # folds is heavily biased against non-zero models due to rapidly 
        # shrinking risk sets. 
        # We compute the validation LL using the glmnet standard: apply the 
        # fold's betas to the full dataset, and subtract the log-likelihood 
        # of the training data.
        ll_full  = partial_loglik(beta_j, X_std, t_all, e_float) * e_float.sum()
        ll_train = partial_loglik(beta_j, X_tr, t_tr, e_tr) * e_tr.sum()
        
        cv_scores[k, j] = (ll_full - ll_train) / e_va.sum()

    print(f" fold{k+1}", end="", flush=True)

print(" done")

cv_mean  = cv_scores.mean(axis=0)
cv_se    = cv_scores.std(axis=0) / np.sqrt(K)
best_j   = np.argmax(cv_mean)
lam_best = lam_grid[best_j]
threshold = cv_mean[best_j] - cv_se[best_j]
one_se_j  = np.where(cv_mean >= threshold)[0][0]
lam_1se   = lam_grid[one_se_j]

print(f"\nlambda_min = {lam_best:.5f}  (index {best_j})")
print(f"lambda_1SE = {lam_1se:.5f}  (index {one_se_j})")

# ═══════════════════════════════════════════════════════════════════════════════
# 5.  REFIT ON FULL DATA at selected λ values
# ═══════════════════════════════════════════════════════════════════════════════
def refit_at_alpha(alpha):
    m = CoxnetSurvivalAnalysis(
        l1_ratio=1.0,
        alphas=[float(alpha)],
        normalize=False,
        fit_baseline_model=False,
        max_iter=200_000,
        tol=1e-10,
    )
    m.fit(X_std, y_surv)
    return m.coef_.ravel()

beta_min_std  = refit_at_alpha(lam_best)
beta_1se_std  = refit_at_alpha(lam_1se)
beta_min      = beta_min_std / X_sd_full
beta_1se      = beta_1se_std / X_sd_full
n_nonzero_min = int(np.sum(np.abs(beta_min_std) > 1e-6))
n_nonzero_1se = int(np.sum(np.abs(beta_1se_std) > 1e-6))

# ═══════════════════════════════════════════════════════════════════════════════
# 6.  POST-FIT CHECKS
# ═══════════════════════════════════════════════════════════════════════════════
print("\n" + "─" * 60)
print("  POST-FIT DIAGNOSTIC CHECKS  (lambda_min model)")
print("─" * 60)
COEF_THRESHOLD = 5.0
print(f"\n[Check 2] Runaway coefficients (|beta_std| > {COEF_THRESHOLD}):")
runaway = np.where(np.abs(beta_min_std) > COEF_THRESHOLD)[0]
if len(runaway):
    for k in runaway:
        print(f"  [WARNING] '{COVARIATE_NAMES[k]}':  "
              f"beta_std={beta_min_std[k]:+.3f},  beta_orig={beta_min[k]:+.3f}")
else:
    print("  No runaway coefficients detected.")
top_k = np.argmax(np.abs(beta_min_std))
print(f"\n  Largest |beta_std|: '{COVARIATE_NAMES[top_k]}' = "
      f"{beta_min_std[top_k]:+.4f}")
print("─" * 60 + "\n")

# ═══════════════════════════════════════════════════════════════════════════════
# 7.  BOOTSTRAP 95% CIs  (λ_min model, fixed-λ)
#
#     Resampling is at the subject level (rows of X_std).  Each row already
#     encodes that subject's TV term x_j*log(t_i), so the bootstrap sample
#     X_b = X_std[idx_b] inherits the correct TV value for each resampled
#     subject without any re-expansion step.
# ═══════════════════════════════════════════════════════════════════════════════
B         = 200
boot_coef = np.zeros((B, p))
print(f"Bootstrap CIs at lambda_min  (B={B})  ...", end="", flush=True)

for b in range(B):
    idx_b = np.random.choice(n, n, replace=True)
    X_b   = X_std[idx_b]
    y_b   = y_surv[idx_b]
    if y_b["event"].sum() < 5:
        boot_coef[b] = beta_min_std
        continue
    bm = CoxnetSurvivalAnalysis(
        l1_ratio=1.0,
        alphas=[float(lam_best)],
        normalize=False,
        fit_baseline_model=False,
        max_iter=100_000,
        tol=1e-7,
    )
    try:
        bm.fit(X_b, y_b)
        boot_coef[b] = bm.coef_.ravel()
    except Exception:
        boot_coef[b] = beta_min_std
    if b % 50 == 0:
        print(".", end="", flush=True)

print(" done")

boot_orig = boot_coef / X_sd_full[None, :]
ci_lo     = np.percentile(boot_orig, 2.5,  axis=0)
ci_hi     = np.percentile(boot_orig, 97.5, axis=0)
hr_min    = np.exp(beta_min)
hr_lo_min = np.exp(ci_lo)
hr_hi_min = np.exp(ci_hi)

# "unpenalized" = coefficients at lam_min (least-regularized point on path)
beta_unpen = path_orig[:, -1]

important_idx = sorted(
    [k for k in range(p) if np.abs(beta_min_std[k]) > 1e-6],
    key=lambda k: abs(beta_min[k]), reverse=True
)

# ═══════════════════════════════════════════════════════════════════════════════
# 8.  CONSOLE SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════
print("\n" + "═" * 74)
print("  LASSO-PENALIZED COX PH MODEL (scikit-survival) — Summary")
print("═" * 74)
print(f"  lambda_min = {lam_best:.5f}  → {n_nonzero_min} non-zero  |  "
      f"lambda_1SE = {lam_1se:.5f}  → {n_nonzero_1se} non-zero")
print("\n  Reference categories:")
print("    region          → Africa (code 4)")
print("    incompatibility → Territory (code 1)")
print("    pa_type         → Full agreement (code 1)")
print("    frame           → Frame type 1 (code 1)")
print(f"\n── lambda_min model  (sorted by signed magnitude) ─────────────────────────────")
print(f"  {'Covariate':<47} {'beta':>8}  {'HR':>7}  95% Boot CI")
print("  " + "─" * 72)
for k in sorted(range(p), key=lambda k: beta_min[k], reverse=True):
    if abs(beta_min[k]) < 1e-6:
        continue
    b, hr  = beta_min[k], hr_min[k]
    lo, hi = hr_lo_min[k], hr_hi_min[k]
    sig    = "  ***" if (lo > 1 or hi < 1) else ""
    tv_tag = "  [tv]" if COVARIATE_NAMES[k] in TV_NAMES else ""
    print(f"  {LABELS[COVARIATE_NAMES[k]]:<47} {b:+8.4f}  {hr:7.3f}"
          f"  ({lo:.3f}-{hi:.3f}){sig}{tv_tag}")

zeroed = [COVARIATE_NAMES[k] for k in range(p) if abs(beta_min[k]) < 1e-6]
print(f"\n  Zeroed-out ({len(zeroed)}): {', '.join(zeroed)}\n")

# ── Covariate×covariate interaction selection summary ────────────────────────
selected_interactions = [
    iname for iname in INTERACTION_NAMES
    if abs(beta_min[COVARIATE_NAMES.index(iname)]) > 1e-6
]
zeroed_interactions = [i for i in INTERACTION_NAMES if i not in selected_interactions]
if INTERACTIONS:
    print(f"  Selected covariate interactions ({len(selected_interactions)}): "
          f"{', '.join(selected_interactions) or 'none'}")
    print(f"  Zeroed covariate interactions  ({len(zeroed_interactions)}): "
          f"{', '.join(zeroed_interactions) or 'none'}")

# ── Time-varying term selection summary ──────────────────────────────────────
# For PH-violating variables, the base term and its time interaction should
# ideally be interpreted as a pair (effect = beta_1 + beta_2*log(t)).
# Report which base/TV pairs were fully selected, partially selected, or zeroed.
if TV_NAMES:
    print(f"\n── Time-varying term selection  [tv] = x*log(t) residualised ────────")
    print(f"  {'Variable':<35} {'Base selected':>14}  {'TV selected':>12}")
    print("  " + "─" * 64)
    for v in VIOLATORS:
        tname     = f"{v}:log(t)"
        base_sel  = abs(beta_min[COVARIATE_NAMES.index(v)])     > 1e-6
        tv_sel    = abs(beta_min[COVARIATE_NAMES.index(tname)]) > 1e-6
        base_str  = "yes" if base_sel else "zeroed"
        tv_str    = "yes" if tv_sel   else "zeroed"
        note = ""
        if tv_sel and not base_sel:
            note = "  [!] TV retained, base zeroed — interpret beta_2 alone as "  \
                   "effect change per log(t) unit vs. baseline of 0"
        print(f"  {v:<35} {base_str:>14}  {tv_str:>12}{note}")
    print(f"\n  [tv] interpretation: effect of x at time t = "
          f"beta_1 + beta_2 * log(t+1)\n"
          f"  beta_1 only meaningful when log(t+1) = 0, i.e. t = 0 days.")

# ═══════════════════════════════════════════════════════════════════════════════
# 9.  FIGURES  (identical layout/style to custom version)
# ═══════════════════════════════════════════════════════════════════════════════
plt.rcParams.update({
    "font.family":       "serif",
    "font.serif":        ["Georgia", "Times New Roman", "DejaVu Serif"],
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.color":        "#e0dcd5",
    "grid.linewidth":    0.55,
    "grid.linestyle":    "--",
    "figure.facecolor":  "#FAFAF7",
    "axes.facecolor":    "#FAFAF7",
    "axes.labelcolor":   "#2b2b2b",
    "xtick.color":       "#2b2b2b",
    "ytick.color":       "#2b2b2b",
    "text.color":        "#2b2b2b",
})
PALETTE = [
    "#E63946","#2A9D8F","#E9C46A","#457B9D","#F4A261","#6A4C93",
    "#264653","#E76F51","#06D6A0","#F77F00","#118AB2","#EF233C",
    "#8338EC","#3A86FF","#FB8500","#023047","#219EBC","#8ECAE6",
    "#606C38","#DDA15E",
]
imp_color = {k: PALETTE[i % len(PALETTE)] for i, k in enumerate(important_idx)}
n_show    = len(important_idx)
fig_h     = max(18, 4 + n_show * 0.55)
fig       = plt.figure(figsize=(20, fig_h), facecolor="#FAFAF7")
fig.suptitle(
    "Lasso-Penalized Cox PH (scikit-survival) — Peace Agreement Duration  "
    f"({p} predictors → {n_nonzero_min} selected at lambda_min)",
    fontsize=16, fontweight="bold", y=0.998, color="#1a1a1a",
)
fig.text(0.5, 0.983,
         f"lambda_min={lam_best:.4f} | lambda_1SE={lam_1se:.4f} | "
         f"Bootstrap 95% CIs (B={B}) | Event: agreement collapse"
         + (f" | {len(TV_NAMES)} TV term(s) residualised" if TV_NAMES else ""),
         ha="center", fontsize=9.5, color="#555", style="italic")

gs      = fig.add_gridspec(2, 2, hspace=0.40, wspace=0.61)
ax_path = fig.add_subplot(gs[0, 0])
ax_cv   = fig.add_subplot(gs[0, 1])
ax_fp   = fig.add_subplot(gs[1, 0])
ax_imp  = fig.add_subplot(gs[1, 1])

log_lam = np.log(lam_grid)

# ── A. Coefficient path ───────────────────────────────────────────────────────
# color TV-term paths differently (dashed) so they are visually distinct from
# base-term paths in the same plot.
for k in range(p):
    if k not in imp_color:
        ax_path.plot(log_lam, path_orig[k, :],
                     color="#d0d0d0", lw=0.7, alpha=0.45, zorder=1)
for k in important_idx:
    is_tv = COVARIATE_NAMES[k] in TV_NAMES
    ax_path.plot(log_lam, path_orig[k, :],
                 color=imp_color[k], lw=2.2, alpha=0.95, zorder=3,
                 linestyle="--" if is_tv else "-")

ax_path.axvline(np.log(lam_best), color="#333", lw=1.4, ls="--",
                label=f"lambda_min  ({n_nonzero_min} predictors)", zorder=4)
ax_path.axvline(np.log(lam_1se),  color="#999", lw=1.2, ls=":",
                label=f"lambda_1SE  ({n_nonzero_1se} predictors)", zorder=4)
ax_path.axhline(0, color="#aaa", lw=0.6, zorder=2)

n_active = (np.abs(path_std) > 1e-6).sum(axis=0)   # shape (N_LAM,)
tick_idx = np.linspace(0, N_LAM - 1, 9, dtype=int)
ax2 = ax_path.twiny()
ax2.set_xlim(ax_path.get_xlim())
ax2.set_xticks(log_lam[tick_idx])
ax2.set_xticklabels(n_active[tick_idx], fontsize=7.5)
ax2.set_xlabel("# non-zero coefficients", fontsize=8.5)
ax2.spines["top"].set_visible(True)
ax2.spines["right"].set_visible(False)

ax_path.set_xlabel("log(lambda)  →  increasing regularization", fontsize=10, fontfamily="DejaVu Sans")
ax_path.set_ylabel("Coefficient (original scale)", fontsize=10)
ax_path.set_title("Lasso Coefficient Path\n"
                  "(colored = selected at lambda_min;  grey = zeroed out;"
                  "  dashed = time-varying term)",
                  fontsize=11.5, fontweight="bold", pad=10)

path_legend_handles = [
    plt.Line2D([0], [0],
               color=imp_color[k], lw=2.2,
               linestyle="--" if COVARIATE_NAMES[k] in TV_NAMES else "-",
               label=LABELS[COVARIATE_NAMES[k]].split(" [ref")[0])
    for k in important_idx
]
vline_handles = [
    plt.Line2D([0],[0], color="#333", lw=1.4, ls="--",
               label=f"lambda_min  ({n_nonzero_min} predictors)"),
    plt.Line2D([0],[0], color="#999", lw=1.2, ls=":",
               label=f"lambda_1SE  ({n_nonzero_1se} predictors)"),
]
ax_path.legend(
    handles=vline_handles + path_legend_handles,
    fontsize=7.5, loc="upper left", bbox_to_anchor=(1.02, 1),
    borderaxespad=0, framealpha=0.88, edgecolor="#ccc",
    title="Selected predictors", title_fontsize=8.5,
)

# ── B. Cross-validation curve ─────────────────────────────────────────────────
cv_order   = np.argsort(lam_grid)          # ascending lambda for display
log_lam_cv = np.log(lam_grid[cv_order])
cv_mean_cv = cv_mean[cv_order]
cv_se_cv   = cv_se[cv_order]

ax_cv.plot(log_lam_cv, cv_mean_cv, color="#457B9D", lw=2.2, label="Mean CV log-lik")
ax_cv.fill_between(
    log_lam_cv,
    cv_mean_cv - cv_se_cv,
    cv_mean_cv + cv_se_cv,
    alpha=0.18,
    color="#457B9D",
    label="+/- 1 SE",
)

ax_cv.axvline(np.log(lam_best), color="#E63946", lw=1.6, ls="--",
              label=f"lambda_min = {lam_best:.4f}  ({n_nonzero_min} vars)")
ax_cv.axvline(np.log(lam_1se), color="#2A9D8F", lw=1.4, ls=":",
              label=f"lambda_1SE = {lam_1se:.4f}  ({n_nonzero_1se} vars)")

ymin, ymax = cv_mean_cv.min(), cv_mean_cv.max()
ax_cv.axvspan(log_lam_cv[0], np.log(lam_best), alpha=0.06, color="#E63946", zorder=0)
ax_cv.text((log_lam_cv[0] + np.log(lam_best)) / 2,
           ymin + (ymax - ymin) * 0.06,
           f"{n_nonzero_min} vars\nselected",
           ha="center", fontsize=8, color="#E63946", style="italic")

ax_cv.set_xlabel("log(lambda)  →  increasing regularization", fontsize=10, fontfamily="DejaVu Sans")
ax_cv.set_ylabel("Mean held-out partial log-likelihood", fontsize=10)
ax_cv.set_title(f"{K}-Fold Cross-Validation Curve",
                fontsize=11.5, fontweight="bold", pad=10)
ax_cv.legend(fontsize=9, framealpha=0.88, edgecolor="#ccc")

# ── RE-SORT BY SIGNED MAGNITUDE ───────────────────────────────────────────────
# Sort from most positive (increases risk) to most negative (protects peace)
important_idx = sorted(important_idx, key=lambda k: beta_min[k], reverse=True)

# ── C. Forest plot ────────────────────────────────────────────────────────────
y_pos = np.arange(n_show)[::-1]
for i, (k, yi) in enumerate(zip(important_idx, y_pos)):
    c     = imp_color[k]
    b     = beta_min[k]
    lo    = ci_lo[k]; hi = ci_hi[k]
    excl  = lo > 0 or hi < 0
    is_tv = COVARIATE_NAMES[k] in TV_NAMES
    ax_fp.plot([lo, hi], [yi, yi], color=c, lw=2.4,
               solid_capstyle="round", zorder=3,
               linestyle="--" if is_tv else "-")
    ax_fp.scatter(b, yi, color=c, s=70, zorder=5,
                  marker="s" if is_tv else ("D" if excl else "o"),
                  edgecolors="white", linewidths=0.7)
    ax_fp.text(hi + 0.02, yi,
               f"{b:+.3f} ({lo:+.3f}-{hi:+.3f})",
               va="center", fontsize=5.5, color="#333")
ax_fp.axvline(0.0, color="#888", lw=1.3, ls="--", zorder=1)
ax_fp.set_yticks(y_pos)
ax_fp.set_yticklabels([LABELS[COVARIATE_NAMES[k]] for k in important_idx],
                      fontsize=8.2)
for ytick, k in zip(ax_fp.get_yticklabels(), important_idx):
    ytick.set_color(imp_color[k])
ax_fp.set_xlabel("Coefficient beta  (95% bootstrap CI)", fontsize=10)
ax_fp.set_title(
    f"Forest Plot of {n_nonzero_min} Selected Predictors at lambda_min\n"
    f"(◆ = CI excludes 0; sorted by value)",
    fontsize=11.5, fontweight="bold", pad=10, fontfamily="DejaVu Sans"
)

# ── D. Variable importance ────────────────────────────────────────────────────
# Use [::-1] so Panel D aligns exactly with Panel C's top-down order
y_b   = np.arange(n_show)[::-1]
bw    = 0.38
short = [LABELS[COVARIATE_NAMES[k]].split(" [ref")[0] for k in important_idx]
for i, (k, yi) in enumerate(zip(important_idx, y_b)):
    c     = imp_color[k]
    sign  = np.sign(beta_min[k])
    b_las = abs(beta_min[k])
    b_unp = abs(beta_unpen[k])
    ax_imp.barh(yi + bw / 2, b_las, bw, color=c, alpha=0.90,
                label="Lasso (lambda_min)" if i == 0 else "")
    ax_imp.barh(yi - bw / 2, b_unp, bw, color=c, alpha=0.30,
                label="Unpenalized (lam_min path)" if i == 0 else "")
    d_color = "#C0392B" if sign > 0 else "#1A7A4A"
    ax_imp.text(max(b_las, b_unp) + 0.008, yi,
                " ▲" if sign > 0 else " ▼",
                va="center", fontsize=9, color=d_color, fontweight="bold",
                fontfamily="DejaVu Sans")
ax_imp.set_yticks(y_b)
ax_imp.set_yticklabels(short, fontsize=9.7)
for ytick, k in zip(ax_imp.get_yticklabels(), important_idx):
    ytick.set_color(imp_color[k])
ax_imp.set_xlabel("Coefficient Magnitude", fontsize=10)
ax_imp.set_title(
    "Variable Importance\n"
    "(▲ = increases hazard  /  ▼ = reduces hazard)",
    fontsize=11.5, fontweight="bold", pad=10, fontfamily="DejaVu Sans"
)
legend_handles = [
    Patch(color="#777", alpha=0.90, label="LASSO"),
    Patch(color="#777", alpha=0.30, label="Unpenalized"),
]
ax_imp.legend(handles=legend_handles, fontsize=8.5,
              framealpha=0.88, edgecolor="#ccc", loc="best")

# ── Save ──────────────────────────────────────────────────────────────────────
out = "cox_lasso_results.png"
plt.savefig(out, dpi=180, bbox_inches="tight", facecolor="#FAFAF7")
print(f"\nFigure saved → {out}")
plt.close()